from pydantic_settings import BaseSettings
from pydantic import Field
from typing import Optional

class Settings(BaseSettings):
    OPENAI_API_KEY: str = Field(..., alias="OPENAI_API_KEY")            # OpenAI API 키
    MONGODB_URI: str = Field(..., alias="MONGODB_URI")                 # MongoDB 연결 URL
    MONGODB_DB_NAME: str = Field(..., alias="MONGODB_DB_NAME")         # MongoDB DB 이름
    DIAGNOSIS_MODEL_NAME: str = Field(..., alias="DIAGNOSIS_MODEL_NAME")      # 체질 진단에 사용할 LLM 모델 이름
    RECIPE_MODEL_NAME: str = Field(..., alias="RECIPE_MODEL_NAME")           # 레시피 생성에 사용할 LLM 모델 이름
    RECIPE_MODEL_COMPANY_NAME: str = Field(..., alias="RECIPE_MODEL_COMPANY_NAME") # 레시피 생성에 사용할 LLM 모델 회사 이름
    API_PREFIX: str = Field(..., alias="API_PREFIX")                   # REST API 엔드포인트 경로
    HOST: str = Field(..., alias="HOST")                               # FastAPI 호스트
    PORT: int = Field(..., alias="PORT")                               # FastAPI 포트
    BACKEND_URL: str = Field(..., alias="BACKEND_URL")                 # 백엔드 서비스 API URL
    LANGSMITH_TRACING: bool = Field(False, alias="LANGSMITH_TRACING")  # Langsmith 트레이싱 사용 여부
    LANGSMITH_API_KEY: Optional[str] = Field(None, alias="LANGSMITH_API_KEY") # Langsmith API 키
    LANGSMITH_ENDPOINT: Optional[str] = Field(None, alias="LANGSMITH_ENDPOINT") # Langsmith 엔드포인트
    LANGSMITH_PROJECT_NAME: Optional[str] = Field(None, alias="LANGSMITH_PROJECT_NAME") # Langsmith 프로젝트 이름
    GEMINI_API_KEY: Optional[str] = Field(None, alias="GEMINI_API_KEY") # Gemini API 키
    CLAUDE_API_KEY: Optional[str] = Field(None, alias="CLAUDE_API_KEY")
    CONSTITUTION_DIAGNOSE_ANSWER_PROMPT_NAME: str = Field(..., alias="CONSTITUTION_DIAGNOSE_ANSWER_PROMPT_NAME")
    CONSTITUTION_DIAGNOSE_PROMPT_NAME: str = Field(..., alias="CONSTITUTION_DIAGNOSE_PROMPT_NAME")
    CONSTITUTION_RECIPE_BASE_PROMPT_NAME: str = Field(..., alias="CONSTITUTION_RECIPE_BASE_PROMPT_NAME")
    RECIPE_EVALUATE_QA_PROMPT_NAME: str = Field(..., alias="RECIPE_EVALUATE_QA_PROMPT_NAME")
    RECIPE_EVALUATE_RECIPE_PROMPT_NAME: str = Field(..., alias="RECIPE_EVALUATE_RECIPE_PROMPT_NAME")
    SEOUPSENG_CSV_PATH: str = Field(..., alias="SEOUPSENG_CSV_PATH")
    RECIPE_EVALUATE_LLM_NAME: str = Field(..., alias="RECIPE_EVALUATE_LLM_NAME")
    RECIPE_LLM_NAME: str = Field(..., alias="RECIPE_LLM_NAME")
    CONSTITUTION_RECIPE_ROUTE_SYSTEM_PROMPT_NAME: str = Field(..., alias="CONSTITUTION_RECIPE_ROUTE_SYSTEM_PROMPT_NAME")
    CONSTITUTION_RECIPE_BASE_ASK_PROMPT_NAME: str = Field(..., alias="CONSTITUTION_RECIPE_BASE_ASK_PROMPT_NAME")
    CONSTITUTION_RECIPE_BASE_GENERATE_PROMPT_NAME: str = Field(..., alias="CONSTITUTION_RECIPE_BASE_GENERATE_PROMPT_NAME")
    CONSTITUTION_RECIPE_HISTORY_ABSTRACT_PROMPT_NAME: str = Field(..., alias="CONSTITUTION_RECIPE_HISTORY_ABSTRACT_PROMPT_NAME")
    CONSTITUTION_RECIPE_REWRITE_FOR_WEB_PROMPT_NAME: str = Field(..., alias="CONSTITUTION_RECIPE_REWRITE_FOR_WEB_PROMPT_NAME")
    CONSTITUTION_RECIPE_DOC_RELEVANCE_PROMPT_NAME: str = Field(..., alias="CONSTITUTION_RECIPE_DOC_RELEVANCE_PROMPT_NAME")
    CONSTITUTION_RECIPE_USER_CONTEXT_PROMPT_NAME: str = Field(..., alias="CONSTITUTION_RECIPE_USER_CONTEXT_PROMPT_NAME")
    class Config:
        env_file = ".env"
        env_file_encoding = "utf-8"
        extra = "ignore"

# 환경 변수 로드
settings = Settings()

OPENAI_API_KEY = settings.OPENAI_API_KEY
MONGODB_URI = settings.MONGODB_URI
MONGODB_DB_NAME = settings.MONGODB_DB_NAME
DIAGNOSIS_MODEL_NAME = settings.DIAGNOSIS_MODEL_NAME
RECIPE_MODEL_NAME = settings.RECIPE_MODEL_NAME
RECIPE_MODEL_COMPANY_NAME = settings.RECIPE_MODEL_COMPANY_NAME
API_PREFIX = settings.API_PREFIX
HOST = settings.HOST
PORT = settings.PORT
BACKEND_URL = settings.BACKEND_URL
LANGSMITH_TRACING = settings.LANGSMITH_TRACING
LANGSMITH_API_KEY = settings.LANGSMITH_API_KEY
LANGSMITH_ENDPOINT = settings.LANGSMITH_ENDPOINT
LANGSMITH_PROJECT_NAME = settings.LANGSMITH_PROJECT_NAME
GEMINI_API_KEY = settings.GEMINI_API_KEY
CLAUDE_API_KEY = settings.CLAUDE_API_KEY
CONSTITUTION_DIAGNOSE_ANSWER_PROMPT_NAME = settings.CONSTITUTION_DIAGNOSE_ANSWER_PROMPT_NAME
CONSTITUTION_DIAGNOSE_PROMPT_NAME = settings.CONSTITUTION_DIAGNOSE_PROMPT_NAME
CONSTITUTION_RECIPE_BASE_PROMPT_NAME = settings.CONSTITUTION_RECIPE_BASE_PROMPT_NAME
RECIPE_EVALUATE_QA_PROMPT_NAME = settings.RECIPE_EVALUATE_QA_PROMPT_NAME
RECIPE_EVALUATE_RECIPE_PROMPT_NAME = settings.RECIPE_EVALUATE_RECIPE_PROMPT_NAME
SEOUPSENG_CSV_PATH = settings.SEOUPSENG_CSV_PATH
RECIPE_EVALUATE_LLM_NAME = settings.RECIPE_EVALUATE_LLM_NAME
RECIPE_LLM_NAME = settings.RECIPE_LLM_NAME
CONSTITUTION_RECIPE_ROUTE_SYSTEM_PROMPT_NAME = settings.CONSTITUTION_RECIPE_ROUTE_SYSTEM_PROMPT_NAME
CONSTITUTION_RECIPE_BASE_ASK_PROMPT_NAME = settings.CONSTITUTION_RECIPE_BASE_ASK_PROMPT_NAME
CONSTITUTION_RECIPE_BASE_GENERATE_PROMPT_NAME = settings.CONSTITUTION_RECIPE_BASE_GENERATE_PROMPT_NAME
CONSTITUTION_RECIPE_HISTORY_ABSTRACT_PROMPT_NAME = settings.CONSTITUTION_RECIPE_HISTORY_ABSTRACT_PROMPT_NAME
CONSTITUTION_RECIPE_REWRITE_FOR_WEB_PROMPT_NAME = settings.CONSTITUTION_RECIPE_REWRITE_FOR_WEB_PROMPT_NAME
CONSTITUTION_RECIPE_DOC_RELEVANCE_PROMPT_NAME = settings.CONSTITUTION_RECIPE_DOC_RELEVANCE_PROMPT_NAME
CONSTITUTION_RECIPE_USER_CONTEXT_PROMPT_NAME = settings.CONSTITUTION_RECIPE_USER_CONTEXT_PROMPT_NAME